ARG ENV_MODE=production
FROM node:16 AS base

FROM base AS development
WORKDIR /app
COPY ./frontend/package*.json .
RUN npm install
COPY ./frontend .
CMD ["npm", "run", "dev"]  # 启动开发服务器（如Vite）

FROM base AS production
WORKDIR /app
COPY ./frontend .
RUN npm install && npm run build
CMD ["npm", "run", "preview"]  # 生产环境预览