#version: '3'  # 新版本Docker Compose(v2+) 已废弃 version 字段

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: ${ENV_MODE:-production}
    container_name: wjx-backend
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LLM_PROVIDER=${LLM_PROVIDER:-}
      - LLM_API_KEY=${LLM_API_KEY:-}
      - LLM_MODEL=${LLM_MODEL:-}
      - USE_PROXY=${USE_PROXY:-false}
      - DEFAULT_PROXY_URL=${DEFAULT_PROXY_URL:-}

    networks:
      - wjx-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 512M

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: ${ENV_MODE:-production}
    container_name: wjx-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend
    environment:
      - API_URL=${API_URL:-http://backend:5000}
      - NODE_ENV=${NODE_ENV:-production}

    networks:
      - wjx-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 128M

# No need for named volumes as we're using bind mounts

networks:
  wjx-network:
    driver: bridge
