version: '3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: wjx-backend
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: wjx-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
